# -*- coding: utf-8 -*-
"""InterpolationSearch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wFzOARXd0vTi8PmoC4mV57XFw2i3fwSv
"""

def interpolationSearch(arr, length, x):  
	low = 0
	high = (length - 1) 

	while low <= high and x >= arr[low] and x <= arr[high]: 
		if low == high: 
			if arr[low] == x: 
				return low; 
			return -1;  
		pos = low + int(((float(high - low) /
			( arr[high] - arr[low])) * ( x - arr[low]))) 

		if arr[pos] == x: 
			return pos 

		if arr[pos] < x: 
			low = pos + 1; 

		else: 
			high = pos - 1; 
	
	return -1

arr = [110, 120, 183, 126, 518, 419, 220, \
              521, 222, 236, 724, 373, 315, 442, 479] 
length = len(arr) 

x = 479
index = interpolationSearch(arr, length, x) 

if index != -1: 
	print ("Element is found at index",index )
else: 
	print ("Element was not found" )