# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W2P2nxzaV_t_ePeJDnZMmbLkhvRxqZaF
"""

#used for quick sort algo
#pivot is taken as last element
def lomutoPartition(arr,l,h):
  pivot=arr[h]
  i=l-1
  for j in range(l,h):
    if arr[j]<pivot:
      i=i+1
      arr[i],arr[j]=arr[j],arr[i]
  arr[i+1],arr[h]=arr[h],arr[i+1]
  return i+1

def qsort(arr,l,h):
  if l<h:
    p=lomutoPartition(arr,l,h)
    qsort(arr,l,p-1)
    qsort(arr,p+1,h)

#divercode
arr=[10,3,4,29,5,51]
l=0
h=len(arr)-1
qsort(arr,l,h)