name: Push Event Workflow

on: push
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Install Package
      run: pip install pytest
      
    - name: flake8 
      run: py-actions/flake8@v2
      
    - name: Run tests
      run: pytest reverse_recursion_test.py
      
